# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"rgb2gray": "00_core.ipynb",
         "otsu_thresh_4largest_component": "00_core.ipynb",
         "component_closest_center": "00_core.ipynb",
         "get_center": "00_core.ipynb",
         "denormalizePatches": "00_core.ipynb",
         "figs_horizontal2": "00_core.ipynb",
         "figs_comparison": "00_core.ipynb",
         "figs_horizontal3": "00_core.ipynb",
         "plot_inpaints_pairs": "00_core.ipynb",
         "add_module": "01_models.common.ipynb",
         "Concat": "01_models.common.ipynb",
         "GenNoise": "01_models.common.ipynb",
         "Swish": "01_models.common.ipynb",
         "act": "01_models.common.ipynb",
         "bn": "01_models.common.ipynb",
         "conv": "01_models.common.ipynb",
         "torch.nn.Module.add": "01_models.common.ipynb",
         "Downsampler": "01_models.common.ipynb",
         "skip": "01_models.skip.ipynb"}

modules = ["core.py",
           "models/common.py",
           "models/skip.py"]

doc_url = "https://octaviomtz.github.io/inpaint_melanoma/"

git_url = "https://github.com/octaviomtz/inpaint_melanoma/tree/master/"

def custom_doc_links(name): return None
