# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"rgb2gray": "00_core.ipynb",
         "otsu_thresh_4largest_component": "00_core.ipynb",
         "component_closest_center": "00_core.ipynb",
         "get_center": "00_core.ipynb",
         "denormalizePatches": "00_core.ipynb",
         "figs_horizontal2": "00_core.ipynb",
         "figs_comparison": "00_core.ipynb",
         "figs_horizontal3": "00_core.ipynb",
         "plot_inpaints_pairs": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://octaviomtz.github.io/inpaint_melanoma/"

git_url = "https://github.com/octaviomtz/inpaint_melanoma/tree/master/"

def custom_doc_links(name): return None
