# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"rgb2gray": "00_core.ipynb",
         "otsu_thresh_4largest_component": "00_core.ipynb",
         "component_closest_center": "00_core.ipynb",
         "get_center": "00_core.ipynb",
         "denormalizePatches": "00_core.ipynb",
         "figs_horizontal2": "00_core.ipynb",
         "figs_comparison": "00_core.ipynb",
         "figs_horizontal3": "00_core.ipynb",
         "plot_inpaints_pairs": "00_core.ipynb",
         "add_module": "01_common.ipynb",
         "Concat": "01_common.ipynb",
         "GenNoise": "01_common.ipynb",
         "Swish": "01_common.ipynb",
         "act": "01_common.ipynb",
         "bn": "01_common.ipynb",
         "conv": "01_common.ipynb",
         "torch.nn.Module.add": "01_common.ipynb",
         "Downsampler": "03_downsampler.ipynb",
         "skip": "02_skip.ipynb",
         "get_kernel": "03_downsampler.ipynb",
         "get_text_mask": "04_inpainting_utils.ipynb",
         "get_bernoulli_mask": "04_inpainting_utils.ipynb",
         "crop_image": "05_common_utils.ipynb",
         "get_params": "05_common_utils.ipynb",
         "get_image_grid": "05_common_utils.ipynb",
         "plot_image_grid": "05_common_utils.ipynb",
         "load": "05_common_utils.ipynb",
         "get_image": "05_common_utils.ipynb",
         "fill_noise": "05_common_utils.ipynb",
         "get_noise": "05_common_utils.ipynb",
         "get_noise2": "05_common_utils.ipynb",
         "pil_to_np": "05_common_utils.ipynb",
         "np_to_pil": "05_common_utils.ipynb",
         "np_to_torch": "05_common_utils.ipynb",
         "torch_to_np": "05_common_utils.ipynb",
         "optimize": "05_common_utils.ipynb",
         "plot_for_gif": "05_common_utils.ipynb",
         "adjust_learning_rate": "05_common_utils.ipynb",
         "optimize_melanoma_v1": "05_common_utils.ipynb"}

modules = ["core.py",
           "common.py",
           "skip.py",
           "downsampler.py",
           "inpainting_utils.py",
           "common_utils.py"]

doc_url = "https://octaviomtz.github.io/inpaint_melanoma/"

git_url = "https://github.com/octaviomtz/inpaint_melanoma/tree/master/"

def custom_doc_links(name): return None
